#!/home/repos/public/Python/bin/python3.6
#

from netmiko import Netmiko
from getpass import getpass

def connect_device(device, command):
    host = {"ip":device.strip(), "username":username, "password":password, "device_type":"cisco_ios", "secret":enable}
    
    # for SLOW links
    # host = {"ip":device.strip(), "username":username, "password":password, "device_type":"cisco_ios", "secret":enable, "global_delay_factor":5}
    
    try:
        net_connect = Netmiko(**host)
        net_connect.enable()
        output = net_connect.send_command(command)
        return output
    except Exception as ex:
        print(f"{device} connection FAILED! -  Error message: ", ex)


commands = ["ping 1.1.1.1", "show ip interface brief"]   # sample list of commands
devices = ["device1", "device2"]   # sample list of devices

username = input("Username: ")
password = getpass("TACACS+ Password: ")
enable = getpass("Enable Secret: ")


for device in devices:
    for command in commands:
        print(device)
        print("---------------------------------------------------------------------")
        print(connect_device(device, command))
        print()

