#!/home/repos/public/Python/bin/python3.6
#

import re
from datetime import timedelta
from pysnmp.hlapi import *



class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


def construct_snmp_iterator(device, snmp_oid):
    iterator = f"nextCmd(SnmpEngine(), UsmUserData('{snmp_username}', '{snmp_password}'), UdpTransportTarget(('{device}', 161)), ContextData(), ObjectType(ObjectIdentity('{snmp_oid}')), loo
kupMib=False, lexicographicMode=False)"
    return eval(iterator)


def snmpwalk(device, iterator):
    snmpwalk_response_list = []
    for (errorIndication, errorStatus, errorIndex, varBinds) in iterator:
        if errorIndication:
            print(device, "ERROR: ", errorIndication)
            break

        elif errorStatus:
            print('ERROR STATUS: %s at %s' % (errorStatus.prettyPrint(), errorIndex and varBinds[int(errorIndex) - 1][0] or '?'))
            break

        else:
            for varBind in varBinds:
                snmp_response = ' = '.join([x.prettyPrint() for x in varBind])
                snmpwalk_response_list.append([device, snmp_response])

    return snmpwalk_response_list

def list_bgp_up_less_than_week(devices):
    cbgpPeer2FsmEstablishedTime = "1.3.6.1.4.1.9.9.187.1.2.5.1.19"
    week_in_seconds = 604800
    five_weeks_in_seconds = 3024000
    print("Listing BGP Established neigbors!")
    print("Only if:")
    print("    Uptime is less than a week")
    print("----------------------------------------------------------------------")
    for device in devices:
        iterator = construct_snmp_iterator(device, cbgpPeer2FsmEstablishedTime)
        bgp_estab_time_list = snmpwalk(device, iterator)

        for item in bgp_estab_time_list:
            bgp_estab_time = int(item[-1].split("=")[-1].strip())
            convert = timedelta(seconds=bgp_estab_time)
            if (bgp_estab_time < five_weeks_in_seconds) and (bgp_estab_time != 0):
                bgp_neighbor = re.findall(r'(\d+\.\d+\.\d+\.\d+)$', item[-1].split("=")[0].strip())[0]
                print(f"{device : <32} BGP Neighbor {bgp_neighbor : <15} Uptime is {bcolors.WARNING}{convert}{bcolors.ENDC}")



snmp_username = "<snmp_username>"
snmp_password = "<snmp_password>"
devices = ["device1", "device2"]
list_bgp_up_less_than_week(devices)   # tested for up lest than 5 weeks, modify function accordingly
