#!/home/repos/public/Python/bin/python3.6
#

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def send_mail(mail_text):

    msg = MIMEMultipart('alternative')
    msg['Subject'] = 'Status check cxxxx devices!'
    msg['From'] = '<sender_email_address>'
    msg['To'] = '<receiver1_email_addres>, <receiver2_email_addres>'

    HTML_BODY = MIMEText(mail_text, 'html')
    msg.attach(HTML_BODY)
    s = smtplib.SMTP('localhost')
    s.sendmail(msg['From'], msg['To'].split(','), msg.as_string())


with open("<html_file_full_path>", "r") as m:
    content = m.read()
    send_mail(content)
