#!/home/repos/public/Python/bin/python3.6
#

import subprocess

ip = "1.1.1.1"
png = subprocess.run([f"ping {ip} -c 2 -W 1"], stdout=subprocess.PIPE, check=False, shell=True)
print(png.stdout.decode('utf-8'))  # decoded command output
print(png.args)                    # command itself
print(png.returncode)              # Arguments (0 means success of running command, also success for Ping in this case!!!)
print()
print(png)
print()


orders = subprocess.run(["more <csv_FILE_FULL_PATH> | awk -F ',' '{ print $2 }' | sort -u"], stdout=subprocess.PIPE, check=False, shell=True)
print(orders)
print()
print(orders.stdout.decode('utf-8'))
print()



