#!/home/repos/public/Python/bin/python3.6
#

"""
iterrating over a list to take actions for each and breaking on wrong input
"""

l = ["a","b","c"]

while True:
    result = input("please choose a b or c:  ")
    if result not in l:
        print("WRONG VALUE!!!")
    elif result in l:
        break
